services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/storage:/app/storage
    ports:
      - "8001:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://167.71.232.255:8001
    ports:
      - "3001:80"
    depends_on:
      - backend
    restart: unless-stopped
